import { RanchBotApiClient } from '../../client';

export function createMockClient(): jest.Mocked<RanchBotApiClient> {
  return {
    getFarms: jest.fn(),
    getFarm: jest.fn(),
    getDefaultFarm: jest.fn(),
    setDefaultFarm: jest.fn(),
    listAnimals: jest.fn(),
    getAnimal: jest.fn(),
    createAnimal: jest.fn(),
    updateAnimal: jest.fn(),
    deleteAnimal: jest.fn(),
    findOrCreateAnimalByEid: jest.fn(),
    listAnimalIdentifiers: jest.fn(),
    addAnimalIdentifier: jest.fn(),
    removeAnimalIdentifier: jest.fn(),
    listGroups: jest.fn(),
    listMemories: jest.fn(),
    getGroup: jest.fn(),
    createGroup: jest.fn(),
    updateGroup: jest.fn(),
    deleteGroup: jest.fn(),
    restoreGroup: jest.fn(),
    listRecords: jest.fn(),
    getRecord: jest.fn(),
    createRecord: jest.fn(),
    updateRecord: jest.fn(),
    deleteRecord: jest.fn(),
    listChuteSessions: jest.fn(),
    getChuteSession: jest.fn(),
    listRations: jest.fn(),
    getRation: jest.fn(),
    createRation: jest.fn(),
    listFeedings: jest.fn(),
    getFeeding: jest.fn(),
    createChuteSession: jest.fn(),
    updateChuteSession: jest.fn(),
    listImportRequests: jest.fn(),
    getImportRequest: jest.fn(),
    updateImportRequestStatus: jest.fn(),
  } as unknown as jest.Mocked<RanchBotApiClient>;
}
